name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - uses: cachix/cachix-action@v14
        with:
          name: lilypond
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix flake check
      - run: nix build --print-build-logs
